import { DarkTheme, DefaultTheme, type Theme } from 'expo-router/react-navigation';

export const THEME = {
  light: {
    background: '#ffffff',
    foreground: '#191f28',
    card: '#ffffff',
    cardForeground: '#191f28',
    popover: '#ffffff',
    popoverForeground: '#191f28',
    primary: '#3183f6',
    primaryForeground: '#ffffff',
    secondary: '#f2f4f6',
    secondaryForeground: '#4e5968',
    muted: '#f2f4f6',
    mutedForeground: '#6b7684',
    accent: '#e9f2fe',
    accentForeground: '#2676e2',
    destructive: '#e5484d',
    border: '#e5e8eb',
    input: '#e4e8ed',
    ring: '#3183f6',
    radius: '1rem',
  },
  dark: {
    background: '#121212',
    foreground: '#f2f4f6',
    card: '#191f28',
    cardForeground: '#f2f4f6',
    popover: '#191f28',
    popoverForeground: '#f2f4f6',
    primary: '#5b9cfa',
    primaryForeground: '#071425',
    secondary: '#212529',
    secondaryForeground: '#e5e8eb',
    muted: '#212529',
    mutedForeground: '#b0b8c1',
    accent: '#1f3149',
    accentForeground: '#80b2fb',
    destructive: '#ff6b70',
    border: '#343a40',
    input: '#4e5968',
    ring: '#5b9cfa',
    radius: '1rem',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
